import type { StretchLevelId } from '../types.js'
import type { SafetyCue } from './exercises.js'

// ─────────────────────────────────────────────────────────────────────────────
// Stretch catalog (Phase 18) — plan-as-data, mirroring catalog/exercises.ts.
//
// Animations are authored as joint coordinates in a 0..100 (x) / 0..120 (y)
// space; `StretchAnimation` connects the joints into a figure and tweens between
// frames. Storing joints (not raw SVG) keeps frames tiny and tweenable.
//
// NOTE: these poses are STARTER fidelity — sensible and distinct, but meant to be
// refined later with a visual pose-editor. Each stretch authors a single target
// (holds) or a few key poses (flows); frames are generated by interpolation.
// ─────────────────────────────────────────────────────────────────────────────

export type StretchArea =
  | 'hipFlexors' | 'quads' | 'hamstrings' | 'adductors' | 'glutes' | 'calves'
  | 'chest' | 'thoracic' | 'lats' | 'shoulders' | 'neck'

export type StretchKind = 'hold' | 'flow'

// Camera per stretch — chosen for whichever angle reads clearest.
export type CameraView =
  | 'front' | 'side-left' | 'side-right' | 'three-quarter-left' | 'three-quarter-right'

// Which limbs are toward the viewer this frame. Far limbs render lighter + thinner
// and behind the torso; near limbs solid + on top. The core front/back cue.
export interface LimbDepth { armL?: 'near' | 'far'; armR?: 'near' | 'far'; legL?: 'near' | 'far'; legR?: 'near' | 'far' }

type Pt = [number, number]

export interface Joints {
  head: Pt; neck: Pt; hip: Pt
  shoulderL: Pt; shoulderR: Pt
  elbowL: Pt; elbowR: Pt
  handL: Pt; handR: Pt
  kneeL: Pt; kneeR: Pt
  footL: Pt; footR: Pt
}

export interface StretchPose extends Joints {
  facing?: 'left' | 'right'
  depth?: LimbDepth
}

export interface StretchLevel {
  level: StretchLevelId
  name: string
  view: CameraView
  holdSeconds?: number      // hold stretches
  durationSeconds?: number  // flow stretches
  reps?: number             // flow stretches (optional)
  tempo?: string
  cues: string[]
  frames: StretchPose[]
  videoUrls: string[]
  progressNote: string
}

export interface StretchDef {
  id: string
  name: string
  kind: StretchKind
  area: StretchArea[]
  perSide: boolean
  safetyCues: SafetyCue[]
  startLevel: StretchLevelId
  levels: [StretchLevel, StretchLevel, StretchLevel]
}

export interface StretchRoutine {
  id: string
  name: string
  kind: StretchKind
  description: string
  stretches: StretchDef[]
}

export interface StretchSessionPlan { id: string; name: string; routineIds: string[] }

export interface StretchPlan {
  version: number
  routines: StretchRoutine[]
  sessions: StretchSessionPlan[]
}

// ── Pose helpers ─────────────────────────────────────────────────────────────

const NEUTRAL: Joints = {
  head: [50, 14], neck: [50, 24], hip: [50, 58],
  shoulderL: [42, 28], shoulderR: [58, 28],
  elbowL: [39, 40], elbowR: [61, 40],
  handL: [37, 51], handR: [63, 51],
  kneeL: [45, 82], kneeR: [55, 82],
  footL: [45, 112], footR: [55, 112],
}

const JOINT_KEYS = Object.keys(NEUTRAL) as (keyof Joints)[]

interface Meta { facing?: 'left' | 'right'; depth?: LimbDepth }

function merge(base: Joints, ov: Partial<Joints>): Joints {
  return { ...base, ...ov }
}

function lerpJoints(a: Joints, b: Joints, t: number): Joints {
  const out = {} as Joints
  for (const k of JOINT_KEYS) {
    out[k] = [a[k][0] + (b[k][0] - a[k][0]) * t, a[k][1] + (b[k][1] - a[k][1]) * t]
  }
  return out
}

function withMeta(j: Joints, m: Meta): StretchPose {
  return m.facing || m.depth ? { ...j, ...(m.facing ? { facing: m.facing } : {}), ...(m.depth ? { depth: m.depth } : {}) } : { ...j }
}

// Hold: ease from neutral into the target pose (5 frames). The component
// ping-pongs, so this reads as enter → hold → release.
function holdFrames(target: Partial<Joints>, m: Meta = {}): StretchPose[] {
  const t = merge(NEUTRAL, target)
  return [0, 0.25, 0.5, 0.75, 1].map(f => withMeta(lerpJoints(NEUTRAL, t, f), m))
}

// Flow: walk neutral → key poses with two interpolation steps per segment, so a
// continuous movement sequence loops smoothly (≤3 key poses → 6–10 frames).
function flowFrames(keys: Partial<Joints>[], m: Meta = {}): StretchPose[] {
  const anchors = [NEUTRAL, ...keys.map(k => merge(NEUTRAL, k))]
  const frames: StretchPose[] = []
  for (let i = 0; i < anchors.length - 1; i++) {
    frames.push(withMeta(anchors[i], m))
    frames.push(withMeta(lerpJoints(anchors[i], anchors[i + 1], 1 / 3), m))
    frames.push(withMeta(lerpJoints(anchors[i], anchors[i + 1], 2 / 3), m))
  }
  frames.push(withMeta(anchors[anchors.length - 1], m))
  return frames
}

// Functional placeholder video: a YouTube search for the movement. Real curated
// Shorts should replace these (kept honest — a search, not a fabricated link).
function vid(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query + ' stretch tutorial')}`
}

interface LevelText { name: string; secs: number; cues: string[]; video: string; progressNote: string }

function holdStretch(
  def: { id: string; name: string; area: StretchArea[]; perSide: boolean; safetyCues: SafetyCue[]; view: CameraView },
  target: Partial<Joints>, meta: Meta, texts: [LevelText, LevelText, LevelText],
): StretchDef {
  const frames = holdFrames(target, meta)
  const levels = texts.map((t, i) => ({
    level: (i + 1) as StretchLevelId, name: t.name, view: def.view,
    holdSeconds: t.secs, cues: t.cues, frames, videoUrls: [t.video], progressNote: t.progressNote,
  })) as [StretchLevel, StretchLevel, StretchLevel]
  return { id: def.id, name: def.name, kind: 'hold', area: def.area, perSide: def.perSide, safetyCues: def.safetyCues, startLevel: 1, levels }
}

function flowStretch(
  def: { id: string; name: string; area: StretchArea[]; perSide: boolean; safetyCues: SafetyCue[]; view: CameraView },
  keys: Partial<Joints>[], meta: Meta, texts: [LevelText, LevelText, LevelText],
): StretchDef {
  const frames = flowFrames(keys, meta)
  const levels = texts.map((t, i) => ({
    level: (i + 1) as StretchLevelId, name: t.name, view: def.view,
    durationSeconds: t.secs, cues: t.cues, frames, videoUrls: [t.video], progressNote: t.progressNote,
  })) as [StretchLevel, StretchLevel, StretchLevel]
  return { id: def.id, name: def.name, kind: 'flow', area: def.area, perSide: def.perSide, safetyCues: def.safetyCues, startLevel: 1, levels }
}

// ── Static-holds routine ─────────────────────────────────────────────────────

const HOLD_STRETCHES: StretchDef[] = [
  holdStretch(
    { id: 'quad', name: 'Quad / hip-front', area: ['quads', 'hipFlexors'], perSide: true, safetyCues: ['knee'], view: 'three-quarter-right' },
    { footR: [56, 58], kneeR: [54, 84], handR: [58, 56], elbowR: [64, 50], handL: [30, 32], elbowL: [36, 36] },
    { facing: 'right', depth: { legR: 'far', armL: 'near', armR: 'near', legL: 'near' } },
    [
      { name: 'Supported standing quad', secs: 25, cues: ['Hold a wall for balance', 'Heel to glute, knees together', 'Tuck the pelvis — no arching'], video: vid('standing quad'), progressNote: 'Ready when balance is easy and the heel reaches the glute.' },
      { name: 'Free-standing quad', secs: 30, cues: ['No support', 'Soft bend in the standing knee', 'Ribs down, glute squeezed'], video: vid('standing quad'), progressNote: 'Ready when you can hold steady and it feels mild.' },
      { name: 'Couch / elevated-foot quad', secs: 30, cues: ['Rear foot on a low step', 'Half-kneel, tall torso', 'Deeper hip-flexor + quad stretch'], video: vid('couch quad'), progressNote: 'Top level — keep control and breathe.' },
    ],
  ),
  holdStretch(
    { id: 'hip-flexor', name: 'Hip flexors', area: ['hipFlexors'], perSide: true, safetyCues: ['back'], view: 'three-quarter-right' },
    { kneeL: [44, 90], footL: [42, 112], kneeR: [60, 104], footR: [70, 112], hip: [50, 66], handL: [44, 8], handR: [56, 8], elbowL: [45, 18], elbowR: [55, 18], shoulderL: [46, 26], shoulderR: [54, 26] },
    { facing: 'right', depth: { legR: 'far' } },
    [
      { name: 'Half-kneeling hip flexor', secs: 30, cues: ['Squeeze the back glute', 'Hips drift forward', 'Ribs down — no arch'], video: vid('kneeling hip flexor'), progressNote: 'Ready when the front of the hip stretches without low-back pinch.' },
      { name: '+ overhead reach & side-bend', secs: 30, cues: ['Same base position', 'Raise the same-side arm', 'Bend gently away'], video: vid('kneeling hip flexor reach'), progressNote: 'Ready when the reach feels controlled.' },
      { name: 'Couch-stretch hip flexor', secs: 30, cues: ['Rear shin up a wall/couch', 'Tall torso', 'Strong hip-flexor + quad'], video: vid('couch stretch'), progressNote: 'Top level — ease in slowly.' },
    ],
  ),
  holdStretch(
    { id: 'hamstring', name: 'Hamstrings', area: ['hamstrings'], perSide: true, safetyCues: ['back'], view: 'three-quarter-right' },
    { footR: [62, 112], kneeR: [58, 90], hip: [44, 58], neck: [64, 40], head: [68, 34], shoulderL: [58, 42], shoulderR: [70, 42], elbowL: [60, 50], elbowR: [68, 50], handL: [60, 58], handR: [66, 58] },
    { facing: 'right' },
    [
      { name: 'Standing flat-back hinge', secs: 25, cues: ['Heel forward, toes up', 'Hinge at the hips — FLAT BACK', 'Chest tall, hands on thigh'], video: vid('standing hamstring flat back'), progressNote: 'Ready when you reach mid-shin with a flat back.' },
      { name: 'Heel elevated, reach to shin', secs: 30, cues: ['Front heel on a low edge', 'Deeper flat-back hinge', 'Hands slide toward the shin'], video: vid('hamstring stretch heel elevated'), progressNote: 'Ready when the deeper hinge stays flat-backed.' },
      { name: 'Supported single-leg with strap', secs: 30, cues: ['Strap around the foot', 'Flat back, draw toes back', 'Controlled deeper range'], video: vid('hamstring strap stretch'), progressNote: 'Top level — never round the back.' },
    ],
  ),
  holdStretch(
    { id: 'adductor', name: 'Adductors (groin)', area: ['adductors'], perSide: false, safetyCues: ['knee'], view: 'front' },
    { hip: [50, 74], kneeL: [34, 86], kneeR: [66, 86], footL: [47, 98], footR: [53, 98], neck: [50, 58], head: [50, 50], shoulderL: [44, 60], shoulderR: [56, 60], elbowL: [42, 70], elbowR: [58, 70], handL: [45, 84], handR: [55, 84] },
    {},
    [
      { name: 'Seated butterfly', secs: 30, cues: ['Soles together', 'Sit tall, let the knees fall', 'Gentle'], video: vid('butterfly groin'), progressNote: 'Ready when the knees rest low comfortably.' },
      { name: 'Butterfly + flat-back hinge', secs: 30, cues: ['Hinge forward — flat back', 'Light elbow press on thighs'], video: vid('butterfly forward fold'), progressNote: 'Ready when the forward hinge feels easy.' },
      { name: 'Supported side-lunge / Cossack', secs: 30, cues: ['Wide stance', 'Shift over a bent knee (knee over toes)', 'Other leg straight, heel down'], video: vid('cossack squat'), progressNote: 'Top level — hold support if needed.' },
    ],
  ),
  holdStretch(
    { id: 'glutes', name: 'Glutes / piriformis', area: ['glutes'], perSide: true, safetyCues: ['back'], view: 'three-quarter-right' },
    { hip: [50, 72], kneeL: [42, 84], footL: [44, 104], kneeR: [40, 80], footR: [36, 84], neck: [50, 58], head: [50, 50], shoulderL: [44, 60], shoulderR: [56, 60], elbowL: [44, 70], elbowR: [56, 70], handL: [42, 80], handR: [52, 78] },
    {},
    [
      { name: 'Lying figure-4', secs: 30, cues: ['Ankle over opposite knee', 'Draw the thigh in', 'Let the crossed knee fall open'], video: vid('figure 4 glute'), progressNote: 'Ready when you draw the thigh toward the chest easily.' },
      { name: 'Seated figure-4, flat-back lean', secs: 30, cues: ['In a chair, ankle on knee', 'Hinge forward — flat back'], video: vid('seated figure 4'), progressNote: 'Ready when the seated version feels mild.' },
      { name: 'Supported pigeon', secs: 30, cues: ['Front shin angled across', 'Hips square, weight off the knee', 'Ease forward'], video: vid('pigeon pose'), progressNote: 'Top level — deepest glute length.' },
    ],
  ),
  holdStretch(
    { id: 'calves', name: 'Calves', area: ['calves'], perSide: true, safetyCues: [], view: 'side-right' },
    { handL: [78, 30], handR: [78, 40], elbowL: [68, 34], elbowR: [68, 44], shoulderL: [58, 30], shoulderR: [62, 30], neck: [58, 26], head: [62, 20], hip: [48, 58], footR: [36, 112], kneeR: [42, 86], footL: [58, 112], kneeL: [54, 84] },
    { facing: 'right' },
    [
      { name: 'Wall calf, straight leg', secs: 30, cues: ['Hands on wall', 'Back leg straight, heel down', 'Hips forward'], video: vid('wall calf'), progressNote: 'Ready when the lean feels mild.' },
      { name: '+ bent-knee soleus', secs: 30, cues: ['Softly bend the back knee', 'Reach the lower calf'], video: vid('soleus calf'), progressNote: 'Ready when both variants feel easy.' },
      { name: 'Heel-drop off a step', secs: 30, cues: ['Forefoot on a step', 'Heel lowers below the edge', 'Hold a rail'], video: vid('calf raise heel drop stretch'), progressNote: 'Top level — controlled range.' },
    ],
  ),
  holdStretch(
    { id: 'chest', name: 'Chest / pecs', area: ['chest', 'shoulders'], perSide: false, safetyCues: [], view: 'front' },
    { handL: [26, 30], handR: [74, 30], elbowL: [30, 36], elbowR: [70, 36], shoulderL: [40, 28], shoulderR: [60, 28], head: [50, 12] },
    { depth: { armL: 'far', armR: 'far' } },
    [
      { name: 'Doorway, forearms low', secs: 30, cues: ['Forearms on the frame, low', 'Step through', 'Shoulders down and back'], video: vid('doorway chest'), progressNote: 'Ready when it feels mild and shoulders stay down.' },
      { name: 'Doorway at shoulder height', secs: 30, cues: ['Elbows ~shoulder height (goalpost)', 'Step through'], video: vid('doorway pec'), progressNote: 'Ready when the higher angle feels easy.' },
      { name: 'Single-arm doorway, rotate away', secs: 30, cues: ['One arm on the frame', 'Rotate the torso away'], video: vid('single arm doorway chest'), progressNote: 'Top level — deeper per-side.' },
    ],
  ),
  holdStretch(
    { id: 'thoracic', name: 'Thoracic rotation', area: ['thoracic', 'shoulders'], perSide: true, safetyCues: [], view: 'side-right' },
    { handR: [78, 16], elbowR: [70, 26], shoulderR: [60, 30], handL: [40, 54], head: [56, 12], neck: [52, 24] },
    { facing: 'right', depth: { armR: 'near' } },
    [
      { name: 'Side-lying open-book', secs: 30, cues: ['Knees stacked and pinned', 'Top arm sweeps open', 'Eyes follow the hand'], video: vid('open book thoracic'), progressNote: 'Ready when the top shoulder nears the floor.' },
      { name: 'Quadruped thread-the-needle', secs: 30, cues: ['On all fours', 'Thread one arm under, then reach up'], video: vid('thread the needle'), progressNote: 'Ready when rotation feels free.' },
      { name: 'Anchored seated twist', secs: 30, cues: ['Rotate and hold a fixed point', 'Tall spine'], video: vid('seated spinal twist'), progressNote: 'Top level — segmental rotation.' },
    ],
  ),
  holdStretch(
    { id: 'lats', name: 'Lats / side-body', area: ['lats'], perSide: true, safetyCues: [], view: 'front' },
    { handR: [40, 6], elbowR: [52, 16], shoulderR: [58, 28], neck: [46, 26], head: [42, 16], hip: [54, 58], handL: [58, 56] },
    { facing: 'left' },
    [
      { name: 'Standing overhead side-bend', secs: 30, cues: ['Hand on hip', 'Reach the other arm up and lean away', 'Long spine'], video: vid('overhead side bend'), progressNote: 'Ready when the reach is easy and even.' },
      { name: 'Clasp wrist overhead, side-bend', secs: 30, cues: ['Opposite hand grips the wrist', 'Gently draw it over'], video: vid('lat side bend'), progressNote: 'Ready when the deeper pull feels mild.' },
      { name: 'Anchored lat hang', secs: 30, cues: ['Hold a post/rail', 'Hips sit back and away', 'Arm long'], video: vid('lat stretch rack'), progressNote: 'Top level — light traction.' },
    ],
  ),
  holdStretch(
    { id: 'shoulders', name: 'Shoulders', area: ['shoulders'], perSide: true, safetyCues: [], view: 'front' },
    { handR: [34, 38], elbowR: [44, 40], shoulderR: [56, 30], handL: [40, 40], elbowL: [40, 46] },
    {},
    [
      { name: 'Cross-body shoulder', secs: 30, cues: ['Draw the arm across the chest', 'Cradle the upper arm (not the elbow)', 'Shoulder down — no shrug'], video: vid('cross body shoulder'), progressNote: 'Ready when the arm crosses easily, shoulder down.' },
      { name: 'Cross-body + deeper draw', secs: 30, cues: ['Draw slightly further', 'Tall posture, relaxed traps'], video: vid('cross body shoulder'), progressNote: 'Ready when the deeper draw feels mild.' },
      { name: 'Supported sleeper stretch', secs: 30, cues: ['Side-lying, elbow out front', 'Gently rotate the forearm down', 'Stop at first tension'], video: vid('sleeper stretch shoulder'), progressNote: 'Top level — easy does it on the joint.' },
    ],
  ),
]

// ── Movement-flow routine ────────────────────────────────────────────────────

const lungeBase: Partial<Joints> = { footL: [44, 112], kneeL: [44, 92], kneeR: [64, 104], footR: [72, 112], hip: [48, 74] }
const quadBase: Partial<Joints> = {
  handL: [34, 100], handR: [34, 100], elbowL: [36, 86], elbowR: [36, 86],
  shoulderL: [40, 72], shoulderR: [40, 72], neck: [44, 70], head: [38, 68],
  hip: [64, 72], kneeL: [68, 90], kneeR: [68, 90], footL: [72, 104], footR: [72, 104],
}

const FLOW_STRETCHES: StretchDef[] = [
  flowStretch(
    { id: 'cars-sequence', name: 'Joint CARs sequence', area: ['shoulders', 'hipFlexors', 'thoracic'], perSide: false, safetyCues: ['back'], view: 'front' },
    [
      { handL: [40, 6], handR: [60, 6], elbowL: [42, 18], elbowR: [58, 18] },
      { handL: [24, 30], handR: [76, 30], elbowL: [33, 32], elbowR: [67, 32] },
      { kneeR: [56, 72], footR: [58, 92] },
    ],
    {},
    [
      { name: 'CARs — major joints', secs: 45, cues: ['Slow controlled circles', 'Neck, shoulders, hips, ankles', 'Biggest circle you can OWN'], video: vid('controlled articular rotations'), progressNote: 'Ready when each circle is smooth and pain-free.' },
      { name: 'CARs — larger + spine & wrists', secs: 45, cues: ['Larger amplitude', 'Add segmental spine + wrists'], video: vid('CARs mobility routine'), progressNote: 'Ready when amplitude is controlled throughout.' },
      { name: 'CARs — full end-range', secs: 45, cues: ['Full end-range circles', 'Brief active hold at end-range'], video: vid('end range CARs'), progressNote: 'Top level — own your full range.' },
    ],
  ),
  flowStretch(
    { id: 'worlds-greatest', name: "World's Greatest Stretch", area: ['hipFlexors', 'thoracic', 'hamstrings', 'glutes'], perSide: false, safetyCues: ['knee', 'back'], view: 'three-quarter-right' },
    [
      { ...lungeBase, handL: [40, 96], handR: [58, 96], elbowL: [41, 86], elbowR: [57, 86], neck: [50, 60], head: [50, 52] },
      { ...lungeBase, handR: [70, 20], elbowR: [62, 34], shoulderR: [58, 40], handL: [44, 96], neck: [52, 58], head: [54, 50] },
    ],
    { facing: 'right' },
    [
      { name: 'Supported lunge + rotation', secs: 40, cues: ['Hand down for support', 'Small open rotation', 'Back knee soft'], video: vid("world's greatest"), progressNote: 'Ready when the lunge + rotation feel stable.' },
      { name: 'Full reach + elbow-to-instep', secs: 40, cues: ['Elbow toward the instep', 'Open reach to the sky'], video: vid("world's greatest stretch"), progressNote: 'Ready when you reach tall with control.' },
      { name: '+ hamstring sweep', secs: 40, cues: ['Straighten the front leg', 'Sweep back over the hamstring', 'Slow tempo'], video: vid("world's greatest stretch advanced"), progressNote: 'Top level — full integrated range.' },
    ],
  ),
  flowStretch(
    { id: 'deep-squat-sit', name: 'Deep-squat sit + reaches', area: ['hipFlexors', 'adductors', 'thoracic', 'calves'], perSide: false, safetyCues: ['knee'], view: 'three-quarter-right' },
    [
      { hip: [50, 84], kneeL: [36, 86], kneeR: [64, 86], footL: [40, 112], footR: [60, 112], neck: [50, 70], head: [50, 62], handL: [44, 80], handR: [56, 80], elbowL: [42, 82], elbowR: [58, 82] },
      { hip: [50, 84], kneeL: [36, 86], kneeR: [64, 86], footL: [40, 112], footR: [60, 112], neck: [52, 68], head: [54, 60], handR: [62, 40], elbowR: [58, 56], handL: [44, 80] },
    ],
    {},
    [
      { name: 'Assisted squat hold', secs: 50, cues: ['Hold support', 'Heels supported if needed', 'Knees track over toes'], video: vid('deep squat mobility'), progressNote: 'Ready when you sit comfortably at depth.' },
      { name: 'Deep squat + alternating reaches', secs: 50, cues: ['Bodyweight deep squat', 'Drive knees out', 'Alternate reaches'], video: vid('deep squat sit'), progressNote: 'Ready when reaches stay balanced.' },
      { name: '+ thoracic rotations & pry', secs: 60, cues: ['Add thoracic rotations', 'Gentle pry with the elbows', 'Longer hold'], video: vid('squat thoracic rotation'), progressNote: 'Top level — deep and controlled.' },
    ],
  ),
  flowStretch(
    { id: '90-90', name: '90/90 hip switches', area: ['glutes', 'hipFlexors'], perSide: false, safetyCues: ['knee'], view: 'front' },
    [
      { hip: [50, 74], kneeL: [36, 80], footL: [28, 86], kneeR: [60, 82], footR: [70, 88], neck: [50, 60], head: [50, 52], handL: [40, 78], handR: [60, 78] },
      { hip: [50, 74], kneeL: [40, 82], footL: [30, 88], kneeR: [64, 80], footR: [72, 86], neck: [50, 60], head: [50, 52], handL: [40, 78], handR: [60, 78] },
    ],
    {},
    [
      { name: 'Small-range switches', secs: 45, cues: ['Hand support', 'Small controlled range', 'Both shins rotate'], video: vid('90 90 hip switch'), progressNote: 'Ready when switching feels smooth.' },
      { name: 'Full switches, unsupported', secs: 45, cues: ['No hands', 'Full range each side'], video: vid('90 90 hip mobility'), progressNote: 'Ready when unsupported switches are easy.' },
      { name: '+ lean & hover', secs: 45, cues: ['Flat-back lean over the front shin', 'Brief hover (active control)'], video: vid('90 90 hip lift off'), progressNote: 'Top level — strong active control.' },
    ],
  ),
  flowStretch(
    { id: 'cossack-flow', name: 'Cossack squat flow', area: ['adductors', 'hipFlexors', 'calves'], perSide: false, safetyCues: ['knee', 'back'], view: 'front' },
    [
      { hip: [36, 80], kneeL: [30, 88], footL: [26, 112], kneeR: [62, 80], footR: [78, 112], neck: [36, 64], head: [36, 56], handL: [30, 72], handR: [44, 70] },
      { hip: [64, 80], kneeR: [70, 88], footR: [74, 112], kneeL: [38, 80], footL: [22, 112], neck: [64, 64], head: [64, 56], handR: [70, 72], handL: [56, 70] },
    ],
    {},
    [
      { name: 'Shallow Cossack, supported', secs: 45, cues: ['Hold support', 'Shift side to side', 'Heel may lift'], video: vid('cossack squat beginner'), progressNote: 'Ready when the shift feels controlled.' },
      { name: 'Deeper, hands free', secs: 45, cues: ['Heel down', 'Hands free', 'Other leg straight'], video: vid('cossack squat'), progressNote: 'Ready when depth is comfortable.' },
      { name: 'Full depth + reach', secs: 45, cues: ['Foot flat at depth', 'Reach forward', 'Slow eccentric'], video: vid('cossack squat mobility'), progressNote: 'Top level — full depth, controlled.' },
    ],
  ),
  flowStretch(
    { id: 'cat-cow-flow', name: 'Cat-cow → segmental flow', area: ['thoracic', 'shoulders'], perSide: false, safetyCues: ['back'], view: 'side-right' },
    [
      { ...quadBase, head: [36, 62], neck: [44, 66], hip: [64, 68] },
      { ...quadBase, head: [40, 76], neck: [46, 74], hip: [62, 78] },
    ],
    { facing: 'right' },
    [
      { name: 'Gentle cat-cow', secs: 45, cues: ['Quadruped spinal wave (unloaded)', 'Move slowly within comfort'], video: vid('cat cow'), progressNote: 'Ready when the wave feels smooth.' },
      { name: '+ thread-the-needle', secs: 45, cues: ['Add a reach-through', 'Open through the upper back'], video: vid('thread the needle flow'), progressNote: 'Ready when reach-throughs feel free.' },
      { name: '+ side-body & segmental wave', secs: 45, cues: ['Add a side-body reach', 'Brief end-range pauses'], video: vid('segmental cat cow flow'), progressNote: 'Top level — full segmental control.' },
    ],
  ),
]

// ── Routines, sessions, plan ─────────────────────────────────────────────────

export const MOVEMENT_FLOW_ROUTINE: StretchRoutine = {
  id: 'movement-flow', name: 'Movement flow', kind: 'flow',
  description: 'Active, full-range movement to open the joints and warm up. Doubles as the dynamic warm-up on training days.',
  stretches: FLOW_STRETCHES,
}

export const FULL_BODY_MOBILITY_ROUTINE: StretchRoutine = {
  id: 'full-body-mobility', name: 'Full-body mobility & flexibility', kind: 'hold',
  description: 'Targeted static holds, head-to-toe. Best done on warm tissue, after the flow.',
  stretches: HOLD_STRETCHES,
}

export const DEFAULT_STRETCH_PLAN: StretchPlan = {
  version: 1,
  routines: [MOVEMENT_FLOW_ROUTINE, FULL_BODY_MOBILITY_ROUTINE],
  sessions: [
    { id: 'daily', name: 'Flow + stretch', routineIds: ['movement-flow', 'full-body-mobility'] },
    { id: 'warmup', name: 'Warm-up flow', routineIds: ['movement-flow'] },
  ],
}

let _liveStretchPlan: StretchPlan | null = null
export function setLiveStretchPlan(plan: StretchPlan): void { _liveStretchPlan = plan }
export function getStretchPlan(): StretchPlan { return _liveStretchPlan ?? DEFAULT_STRETCH_PLAN }
export function getStretchRoutine(id: string): StretchRoutine | undefined { return getStretchPlan().routines.find(r => r.id === id) }
export function getStretch(id: string): StretchDef | undefined { return getStretchPlan().routines.flatMap(r => r.stretches).find(s => s.id === id) }
export function getStretchLevel(s: StretchDef, lvl: StretchLevelId): StretchLevel { return s.levels.find(l => l.level === lvl) ?? s.levels[0] }
export function getStretchSession(id: string): StretchSessionPlan | undefined { return getStretchPlan().sessions.find(s => s.id === id) }
export function getSessionStretches(id: string): StretchDef[] {
  const sp = getStretchSession(id)
  if (!sp) return []
  return sp.routineIds.flatMap(rid => getStretchRoutine(rid)?.stretches ?? [])
}
